project_id = "nitbrsjounnurfjrkwhd"

[functions.room-ai-chat]
verify_jwt = false

[functions.notes-ai]
verify_jwt = false

[functions.analyze-document]
verify_jwt = false

[functions.parse-document]
verify_jwt = false
